name: CI Pipeline

on:
  push:
<<<<<<< HEAD
    branches: ["main, develop"]
=======
    branches: ["develop"]
>>>>>>> e870ef706712bec920b9fd9b281266e4eeb2a923
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: |
          pytest -v
